version: '3.7'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=hu-design-project
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

