url: "mongodb://localhost:27017"
database: "hu-design-project"
userCollection: "user"
devicesCollection: "devices"
requestsCollection: "requests"
alertsCollection: "alert"
blacklistCollection: "blacklist"
whitelistCollection: "whitelist"
